-- -- vim.g.copilot_proxy = 'http://127.0.0.1:8119'
-- local proxy = 'http://127.0.0.1:8118'
-- local p = os.getenv 'http_proxy'
-- if p and p ~= '' then
--     proxy = p
-- end

-- vim.g.copilot_proxy = proxy
-- vim.g.copilot_workspace_folders = { vim.fn.getcwd() }
-- vim.g.copilot_telemetry = 0
--
-- vim.keymap.set('i', '<C-;>', '<Plug>(copilot-next)')
-- vim.keymap.set('i', '<C-/>', '<Plug>(copilot-previous)')
-- vim.keymap.set('i', '<C-]>', '<Plug>(copilot-suggest)')
--
-- vim.keymap.set('i', '<C-.>', '<Plug>(copilot-accept-word)')
-- vim.keymap.set('i', '<C-,>', '<Plug>(copilot-accept-line)')

-- local cmp = require 'cmp'
-- cmp.event:on('menu_opened', function()
--     vim.b.copilot_suggestion_hidden = true
-- end)
--
-- cmp.event:on('menu_closed', function()
--     vim.b.copilot_suggestion_hidden = false
-- end)
--
