-- fuigitive
vim.keymap.set('n', '<leader>gw', ':Git<CR>', { desc = 'Git Status' })
vim.keymap.set('n', '<leader>gg', ':lua _LAZYGIT_TOGGLE()<CR>', { desc = 'Lazygit' })
vim.keymap.set('n', '<leader>gj', function()
    require('gitsigns').next_hunk()
end, { desc = 'Next Hunk' })
vim.keymap.set('n', '<leader>gk', function()
    require('gitsigns').prev_hunk()
end, { desc = 'Prev Hunk' })
vim.keymap.set('n', '<leader>gl', function()
    require('gitsigns').blame_line()
end, { desc = 'Blame' })
vim.keymap.set('n', '<leader>gp', function()
    require('gitsigns').preview_hunk()
end, { desc = 'Preview Hunk' })
vim.keymap.set('n', '<leader>gr', function()
    require('gitsigns').reset_hunk()
end, { desc = 'Reset Hunk' })
vim.keymap.set('n', '<leader>gR', function()
    require('gitsigns').reset_buffer()
end, { desc = 'Reset Buffer' })
vim.keymap.set('n', '<leader>gs', function()
    require('gitsigns').stage_hunk()
end, { desc = 'Stage Hunk' })
vim.keymap.set('n', '<leader>gu', function()
    require('gitsigns').undo_stage_hunk()
end, { desc = 'Undo Stage Hunk' })
vim.keymap.set('n', '<leader>go', ':Telescope git_status<CR>', { desc = 'Open changed file' })
vim.keymap.set('n', '<leader>gb', ':Telescope git_branches<CR>', { desc = 'Checkout branch' })
vim.keymap.set('n', '<leader>gc', ':Telescope git_commits<CR>', { desc = 'Checkout commit' })
vim.keymap.set('n', '<leader>gdd', ':Gitsigns diffthis HEAD<CR>', { desc = 'Diff' })
vim.keymap.set('n', '<leader>gt', ':UndotreeToggle<CR>', { desc = 'undo tree' })

vim.keymap.set('n', '<leader>gds', ':Gvdiffsplit!<CR>', { desc = 'Git Diff' })

--check if is gvdiffsplit screen create a function to call diffget//3 and diffget//2
vim.keymap.set('n', '<leader>gdp', ':diffget //3<CR>', { desc = 'Diffget//3' })
vim.keymap.set('n', '<leader>gdc', ':diffget //2<CR>', { desc = 'Diffget//2' })
